require:
  - rubocop-rake
  - rubocop-rspec
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'tmp/**/*'
  NewCops: enable

RSpec:
  Language:
    Expectations:
      - expected_subprocess
      - expected_exec

Style/FrozenStringLiteralComment:
  Enabled: true

RSpec/AnyInstance:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false
