version: '2'

services:
  app:
    image: ruby:2.3
    environment:
      - GEM_HOME=/bundle
      - BUNDLE_PATH=/bundle
      - HISTFILE=/app/tmp/.bash_history
    working_dir: /app
    volumes:
      - .:/app
      - bundle:/bundle

volumes:
  bundle:
